/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reputationRegistrySol from "./ReputationRegistry.sol";
export type { reputationRegistrySol };
import type * as validationRegistrySol from "./ValidationRegistry.sol";
export type { validationRegistrySol };
export type { AgentRegistry } from "./AgentRegistry";
