[build]
builder = "nixpacks"
buildCommand = "cd Frontend && npm install && npm run build"

[deploy]
startCommand = "cd Frontend && PORT=$PORT npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
