/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
export { ReputationRegistry__factory } from "./ReputationRegistry__factory";
