/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ValidationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAgentValidations"
      | "getSummary"
      | "getValidationStatus"
      | "getValidatorRequests"
      | "validationRequest"
      | "validationResponse"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ValidationRequest" | "ValidationResponse"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgentValidations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values: [BigNumberish, AddressLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validationRequest",
    values: [AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validationResponse",
    values: [BytesLike, BigNumberish, string, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAgentValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getValidationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationResponse",
    data: BytesLike
  ): Result;
}

export namespace ValidationRequestEvent {
  export type InputTuple = [
    validatorAddress: AddressLike,
    agentId: BigNumberish,
    requestURI: string,
    requestHash: BytesLike
  ];
  export type OutputTuple = [
    validatorAddress: string,
    agentId: bigint,
    requestURI: string,
    requestHash: string
  ];
  export interface OutputObject {
    validatorAddress: string;
    agentId: bigint;
    requestURI: string;
    requestHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationResponseEvent {
  export type InputTuple = [
    requestHash: BytesLike,
    response: BigNumberish,
    responseURI: string,
    responseHash: BytesLike,
    tag: string
  ];
  export type OutputTuple = [
    requestHash: string,
    response: bigint,
    responseURI: string,
    responseHash: string,
    tag: string
  ];
  export interface OutputObject {
    requestHash: string;
    response: bigint;
    responseURI: string;
    responseHash: string;
    tag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ValidationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ValidationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgentValidations: TypedContractMethod<
    [agentId: BigNumberish],
    [string[]],
    "view"
  >;

  getSummary: TypedContractMethod<
    [agentId: BigNumberish, validatorAddresses: AddressLike[], tag: string],
    [[bigint, bigint] & { count: bigint; averageResponse: bigint }],
    "view"
  >;

  getValidationStatus: TypedContractMethod<
    [requestHash: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint] & {
        validatorAddress: string;
        agentId: bigint;
        response: bigint;
        responseHash: string;
        tag: string;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;

  getValidatorRequests: TypedContractMethod<
    [validatorAddress: AddressLike],
    [string[]],
    "view"
  >;

  validationRequest: TypedContractMethod<
    [
      validatorAddress: AddressLike,
      agentId: BigNumberish,
      requestURI: string,
      requestHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  validationResponse: TypedContractMethod<
    [
      requestHash: BytesLike,
      response: BigNumberish,
      responseURI: string,
      responseHash: BytesLike,
      tag: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgentValidations"
  ): TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [agentId: BigNumberish, validatorAddresses: AddressLike[], tag: string],
    [[bigint, bigint] & { count: bigint; averageResponse: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidationStatus"
  ): TypedContractMethod<
    [requestHash: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint] & {
        validatorAddress: string;
        agentId: bigint;
        response: bigint;
        responseHash: string;
        tag: string;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorRequests"
  ): TypedContractMethod<[validatorAddress: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "validationRequest"
  ): TypedContractMethod<
    [
      validatorAddress: AddressLike,
      agentId: BigNumberish,
      requestURI: string,
      requestHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validationResponse"
  ): TypedContractMethod<
    [
      requestHash: BytesLike,
      response: BigNumberish,
      responseURI: string,
      responseHash: BytesLike,
      tag: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ValidationRequest"
  ): TypedContractEvent<
    ValidationRequestEvent.InputTuple,
    ValidationRequestEvent.OutputTuple,
    ValidationRequestEvent.OutputObject
  >;
  getEvent(
    key: "ValidationResponse"
  ): TypedContractEvent<
    ValidationResponseEvent.InputTuple,
    ValidationResponseEvent.OutputTuple,
    ValidationResponseEvent.OutputObject
  >;

  filters: {
    "ValidationRequest(address,uint256,string,bytes32)": TypedContractEvent<
      ValidationRequestEvent.InputTuple,
      ValidationRequestEvent.OutputTuple,
      ValidationRequestEvent.OutputObject
    >;
    ValidationRequest: TypedContractEvent<
      ValidationRequestEvent.InputTuple,
      ValidationRequestEvent.OutputTuple,
      ValidationRequestEvent.OutputObject
    >;

    "ValidationResponse(bytes32,uint8,string,bytes32,string)": TypedContractEvent<
      ValidationResponseEvent.InputTuple,
      ValidationResponseEvent.OutputTuple,
      ValidationResponseEvent.OutputObject
    >;
    ValidationResponse: TypedContractEvent<
      ValidationResponseEvent.InputTuple,
      ValidationResponseEvent.OutputTuple,
      ValidationResponseEvent.OutputObject
    >;
  };
}
